/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bjt_ShapeAnalyzer_App */

#ifndef _Included_com_bjt_ShapeAnalyzer_App
#define _Included_com_bjt_ShapeAnalyzer_App
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bjt_ShapeAnalyzer_App
 * Method:    getmaxpercentage
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_com_bjt_ShapeAnalyzer_App_getmaxpercentage
  (JNIEnv *, jclass, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
